import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Header/>
                <main className={'container'}>{children}</main>
                <Footer/>
            </body>
        </html>
    )
}
